# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6689b6a8c20b19baa656da6797a847aae384a7df61854b81026eee3bb74aab0a4ec06969c651d299036c22ded6d30c3c4ffd9bb2a581d3aacf795bb85ced6bac

test:
  secret_key_base: e738b8a00ccb9bdc82ce7f430154aa7f14343c9a8280146dc0259b37dd7bec779877a1e204c2e40ef8bf4ab552a25b00750b0dd25386679cbbd4e08f53a47b68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
